### ISSUE TITLE
自定义组件前缀自定义,注册时当参数传

### ISSUE THREAD

**Issue by minzhenyu** [aisuda/amis-widget#13]
npm-custom这个前缀能自定义吗,注册的时候传进来使用

文档里没写这块内容,很容易造成混淆,
使用时最外层不需要前缀,内部却需要也会混淆,希望能保持一致

**Comment by wibetter** [comment]
这么做就是为了避免自定义组件把Editor预置的组件给覆盖了

**Comment by minzhenyu** [comment]
这个明白,我意思是前缀自己定义,做一些禁用的判断就好了,
或者文档里明确哪些禁用就行了,更或者触发禁用条件就报警告,然后统一默认npm-custom作为前缀

**Comment by wibetter** [comment]
详细的文档这周会抽空编写，预计下周五前会往外放哈，

**Comment by wibetter** [comment]
已剔除默认前缀，生效版本：1.3.7。
