### ISSUE TITLE
editor 自定注册之后可以只作为某个大组件子组件,而不单独展示在自定义组件的列表中,即不展示在tags中,可以吗

### ISSUE THREAD

**Issue by minzhenyu** [aisuda/amis-widget#15]
有时候我只是需要自定义一些小组件,可配置,并不是一定要展示到自定义组件中,有参数可以配置吗

**Comment by wibetter** [comment]
在plugin添加一个属性：disabledRendererPlugin，并设置为true，就不会在组件面板中显示了：
<img width="509" alt="image" src="https://user-images.githubusercontent.com/11958920/163525068-ac135ab6-3e19-482d-b3fe-de0373eb12ec.png">
