### ISSUE TITLE
amis-widget 这个用途是不是想扩展editor, 就不用另外学react了. 会vue就行了.?

### ISSUE THREAD

**Issue by nuan1989** [aisuda/amis-widget#18]
感觉想自己扩展editor, 例子有点少. 
amis真的方便. 很适合我这种不咋会前端的人. 非常谢谢你们团队

**Comment by wibetter** [comment]
目前用vue能扩展大部分场景的组件，但Editor本地是react开发的，所以用react扩展自定义组件自由度会更高。

**Comment by nuan1989** [comment]
> 

国内现在明显vue发展势头更强点. 就有点不想继续学react. 不常用. 学了也会忘记.

**Comment by nuan1989** [comment]
大佬, 文档或者demo有没办法多些, 基础太差. ...

**Comment by wibetter** [comment]
Editor用的是amis渲染器，最好的方式就是阅读代码。

**Comment by wibetter** [comment]
react其实相对vue学习成本不高，对会用vue的人来说，只是多学一个NPM工具包。另外amis-widget-cli同时支持react和vue项目的构建、开发等环境，比较方便来回切换，上手成本不高，有空可以试用下哈。

**Comment by nuan1989** [comment]
> Editor用的是amis渲染器，最好的方式就是阅读代码。

哈哈哈.. 跟大佬不能比不能比.

**Comment by wibetter** [comment]
amis-widget主要用在爱速搭平台中，是为了在不改动平台代码的前提下，通过NPM扩展包的形式在平台中注入自定义组件。
如果只是扩展Editor自定义组件，可以在项目工程中直接开发自定义组件，开发方式可以看下这个文档：https://aisuda.bce.baidu.com/amis/zh-CN/docs/extend/custom-react。

**Comment by nuan1989** [comment]
你好，由于垃圾邮件泛滥，此账号已经停用。
请将邮件重发到
***@***.******@***.*** 
谢谢。

**Comment by Kellercai** [comment]
> amis-widget主要用在爱速搭平台中，是为了在不改动平台代码的前提下，通过NPM扩展包的形式在平台中注入自定义组件。 如果只是扩展Editor自定义组件，可以在项目工程中直接开发自定义组件，开发方式可以看下这个文档：[https://aisuda.bce.baidu.com/amis/zh-CN/docs/extend/custom-react。](https://aisuda.bce.baidu.com/amis/zh-CN/docs/extend/custom-react%E3%80%82)

amis-widget能否用在自研的项目中呢？通过npm包引入自己的平台项目中。

**Comment by wibetter** [comment]
amis-widget目前是开源的，支持在自研项目中使用。
