### ISSUE TITLE
如何把vue的组件的方法/动作暴露给amis其它组件使用

### ISSUE THREAD

**Issue by shuracwf** [aisuda/amis-widget#19]
我有一个vue组件,要如何处理才能实现把方法/动作暴露给其它amis组件使用，其它amis组件可以使用Action来触发，比如下面的例子，我的组件名是tabs-vue，需要使用amis的按纽点击后选中某个选项卡.

`
{
  "type": "page",
  "body": [
    {
      "type": "button",
      "label": "选中选项卡2",
      "level": "primary",
      "className": "mr-3 mb-3",
      "onEvent": {
        "click": {
          "actions": [
            {
              "actionType": "changeActiveKey",
              "componentId": "tabs-change-receiver",
              "args": {
                "activeKey": 2
              }
            }
          ]
        }
      }
    },
    {
      "id": "tabs-change-receiver",
      "type": "tabs-vue",
      "mode": "line",
      "tabs": [
        {
          "title": "选项卡1",
          "body": "选项卡内容1"
        },
        {
          "title": "选项卡2",
          "body": "选项卡内容2"
        },
        {
          "title": "选项卡3",
          "body": "选项卡内容3"
        }
      ]
    }
  ]
}
`

文档里说的如下，但vue的自定义如何处理，请指教。

`
#### 自定义组件接入事件动作
需求场景主要是想要自定义组件的内部事件暴露出去，能够通过对事件的监听来执行所需动作，并希望自定义组件自身的动作能够被其他组件调用。接入方法是通过props.dispatchEvent派发自身的各种事件，使其具备更灵活的交互设计能力；通过实现doAction方法实现其他组件对其专属动作的调用，需要注意的是，此处依赖内部的 Scoped Context来实现自身的注册，可以参考 [组件间通信](https://aisuda.bce.baidu.com/amis/zh-CN/docs/extend/custom-react#%E7%BB%84%E4%BB%B6%E9%97%B4%E9%80%9A%E4%BF%A1)。
`

**Comment by hotlong** [comment]
react 同问

**Comment by minzhenyu** [comment]
+1

**Comment by wibetter** [comment]
一、自定义组件如何使用amis事件动作？
所有组件（**包括自定义组件**）可通过onEvent属性实现渲染器事件与响应动作的绑定。

动作包含通用动作、组件动作、广播动作、自定义动作，可以通过配置actionType来指定具体执行什么动作。
通用动作包含发送 http 请求、跳转链接、浏览器回退、浏览器刷新、打开/关闭弹窗、打开/关闭抽屉、打开对话框、弹出 Toast 提示、复制、发送邮件、刷新、控制显示隐藏、控制启用禁用状态、更新数据。**这些通用动作都是amis内置的，可以在自定义组件中直接使用。（手动配置onEvent）**

自定义组件可通过 props.dispatchEvent 来设置一个渲染器事件（比如 ‘custom-widget-event’），自定义组件本身可以在 onEvent中设置监听这个事件（比如 ‘custom-widget-event’），并关联对应的动作（可以设置amis中通用动作，比如刷新页面）。

二、其他组件如何触发自定义组件的动作？
1、首先自定义组件需要指定 contextType 读取当前的 scope context（static contextType = ScopedContext），并把自己注册在这个scope上（scoped.registerComponent(this)），以便其他组件能通过 componentId 找到这个自定义组件；
2、其次，需要在自定义组件中补充 doAction，用于接收外部组件触发的事件动作，如下所示：
![image](https://user-images.githubusercontent.com/11958920/219315678-f38cbbb8-148d-46de-a20b-4a3f51664a70.png)

3、其他组件可以通过配置componentId来触发自定义组件的动作：
![image](https://user-images.githubusercontent.com/11958920/219315692-eeabe046-120a-42c4-b485-a60180d95f2f.png)


备注1：普通react自定义组件对接amis事件动作示例见 https://github.com/aisuda/react-custom-widget-template/commit/43c637b790ea2ee9f7ff6f8faf654cc82c602101；
备注2：vue自定义组件无需设置ScopedContext，amis-widget会自动设置ScopedContext 【开发中，待发布】。

**Comment by wibetter** [comment]
@shuracwf vue自定义组件对接amis事件动作的示例：https://github.com/aisuda/multiple-custom-widget-template/commit/65c6e8f6fc00cded77a8005ff416fdcc1a5b0
