### ISSUE TITLE
page css 丢失问题

### ISSUE THREAD

**Issue by yyyyzm** [aisuda/amis-widget#21]
在page里面定义css ， 然后就会自动转换丢失， css就没有办法重新定义了，可以帮忙解答一下嘛谢谢啦
![_20230228155531](https://user-images.githubusercontent.com/109934766/221789631-0aefbf3d-8d83-410c-acc4-281ff5a24d4f.png)

![bug](https://user-images.githubusercontent.com/109934766/221789653-88c790fb-688c-4752-a9c0-f40cde344ef7.png)

**Comment by wibetter** [comment]
amis 样式相关用法请看这里：https://aisuda.baidu-int.com/amis/zh-CN/docs/concepts/style
