### ISSUE TITLE
vue项目中安装amis-widget 使用自定义组件一直提示组件名重复怎么解决 

### ISSUE THREAD

**Issue by wlk199718** [aisuda/amis-widget#23]

**Comment by wibetter** [comment]
请简要说一下你的操作步骤，另外说下你用到的自定义组件模板是哪个。
npm list amis-editor看一下版本号是多少；
npm list amis-widget-cli看一下版本号是多少.

**Comment by wlk199718** [comment]
谢谢大佬的回复，场景：我是在vue2中使用
+-- ***@***.***
`-- ***@***.***
&nbsp; `-- ***@***.***

模板是：amis-widget demo里边vue的例子InfoCardPlugin 另外我没安装amis-widget-cli只安装了amis-widget
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aisuda/amis-widget"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月8日(星期三) 上午9:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aisuda/amis-widget] vue项目中安装amis-widget 使用自定义组件一直提示组件名重复怎么解决  (Issue #23)





 
请简要说一下你的操作步骤，另外说下你用到的自定义组件模板是哪个。
 npm list amis-editor看一下版本号是多少；
 npm list amis-widget-cli看一下版本号是多少.

**Comment by wibetter** [comment]
如果是单独跑amis-widget的话，拉一下amis-widget最新代码，重新安装一下依赖，重点要确保amis-editor版本到最新版（5.2.4-beta.31）。
备注：提示组件名重复，一般是因为重复打包了amis-editor或amis。

**Comment by wlk199718** [comment]
不是单独跑是把amis-editor 引入到了vue项目，然后用amis-widget的方式注册自定义组件报错




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aisuda/amis-widget"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月8日(星期三) 下午2:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aisuda/amis-widget] vue项目中安装amis-widget 使用自定义组件一直提示组件名重复怎么解决  (Issue #23)





 
如果是单独跑amis-widget的话，拉一下amis-widget最新代码，重新安装一下依赖，重点要确保amis-editor版本到最新版（5.2.4-beta.31）。
 备注：提示组件名重复，一般是因为重复打包了amis-editor或amis。

**Comment by wlk199718** [comment]
还有大佬问下 amis-widget 和amis-editor是啥关系 amis-widget内部集成了amis-editor吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aisuda/amis-widget"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月8日(星期三) 下午2:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aisuda/amis-widget] vue项目中安装amis-widget 使用自定义组件一直提示组件名重复怎么解决  (Issue #23)





 
如果是单独跑amis-widget的话，拉一下amis-widget最新代码，重新安装一下依赖，重点要确保amis-editor版本到最新版（5.2.4-beta.31）。
 备注：提示组件名重复，一般是因为重复打包了amis-editor或amis。

**Comment by wibetter** [comment]
像你说的问题，一般是打包的问题，你先确认下用到的amis-editor是最新版本，

**Comment by wibetter** [comment]
@wlk199718 请将amis和amis-editor相关模块升级到最新版本，然后再看下是否还有这个问题。之前有部分模块没有支持esm，现在最新版都提供esm模块。
