### ISSUE TITLE
amis-widget只是一个Npm包吗？

### ISSUE THREAD

**Issue by WangHao1221** [aisuda/amis-widget#30]
你好！首先感谢在百忙中恢复我的issue，最近在调研低代码，看到了amis这个产品，感觉很适合我们，现在有几个疑问点，麻烦抽空回复下：（我们的需求其实都用不上这么多组件，只是需要托拉拽针对echarts设置及回显）
1.阅读了下源码amis底层是基于react+ts编写的，我们的项目是vue3+js，直接引入进来的话这种模式是否有文档？还是说我要将ts语法改写为js？
2.amis-widget这个项目clone后是否可以直接运行？（我clone后安装依赖跑起来控制台报错了，所以这个是不是只是纯源码，外部使用直接安装依赖即可）
再次感谢！

**Comment by wibetter** [comment]
1、暂时没有在vue项目中运行amis-editor的指导文档；
2、amis-widget是NPM自定义组件的注册器，内含demo，是可以正常运行起来的，这里地址就是正常运行起来的地址：https://aisuda.github.io/amis-widget/test/preview.html。

**Comment by WangHao1221** [comment]
> 1、暂时没有在vue项目中运行amis-editor的指导文档； 2、amis-widget是NPM自定义组件的注册器，内含demo，是可以正常运行起来的，这里地址就是正常运行起来的地址：[https://aisuda.github.io/amis-widget/test/preview.html。](https://aisuda.github.io/amis-widget/test/preview.html%E3%80%82)

那我可以直接在现有vue3+webpack5+js项目中安装依赖后使用吗？有没有使用方式指点一下？

**Comment by hbkgoing** [comment]
> 你好！首先感谢在百忙中恢复我的issue，最近在调研低代码，看到了amis这个产品，感觉很适合我们，现在有几个疑问点，麻烦抽空回复下：（我们的需求其实都用不上这么多组件，只是需要托拉拽针对echarts设置及回显） 1.阅读了下源码amis底层是基于react+ts编写的，我们的项目是vue3+js，直接引入进来的话这种模式是否有文档？还是说我要将ts语法改写为js？ 2.amis-widget这个项目clone后是否可以直接运行？（我clone后安装依赖跑起来控制台报错了，所以这个是不是只是纯源码，外部使用直接安装依赖即可） 再次感谢！

我直接clone下来也是跑不起来，控制台报错。。。请问怎么怎解决

**Comment by hbkgoing** [comment]
> 1、暂时没有在vue项目中运行amis-editor的指导文档； 2、amis-widget是NPM自定义组件的注册器，内含demo，是可以正常运行起来的，这里地址就是正常运行起来的地址：[https://aisuda.github.io/amis-widget/test/preview.html。](https://aisuda.github.io/amis-widget/test/preview.html%E3%80%82)

请问用amis-widget-cli构建的组件发布到npm上，然后直接引入到包含amis-editor依赖的项目中，是不是可以自动识别组件？

**Comment by wibetter** [comment]
暂时还没有试过在vue3+webpack5+js项目中使用editor。如果使用amis和amis-editor，建议使用react技术栈，对于已有的vue业务内容，可以封装成自定义组件（可使用amis-widget将vue业务组件包装成成react自定义组件）。
