### ISSUE TITLE
master分支启动报错

### ISSUE THREAD

**Issue by hbkgoing** [aisuda/amis-widget#31]
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/32322255/236726124-7cdd22a2-94c4-4b94-96bf-c5b7db7a3bd3.png">

终端尝试执行的命令如下：yarn ; yarn dev

**Comment by hbkgoing** [comment]
![image](https://user-images.githubusercontent.com/32322255/236794220-2d20b7e1-9319-477b-aea0-a54ab55dea26.png)

1.给package.json中添加了 amis-editor跟amis-editor-core的依赖;
2.将 engines中的node版本改为大于等于16.20.0

这样操作过后可以成功运行了，不知为啥，求解

**Comment by wibetter** [comment]
报错的时候，执行下npm list amis和npm list amis-editor看一下当前安装的版本号是多少。

**Comment by yyh1413** [comment]
> 报错的时候，执行下npm list amis和npm list amis-editor看一下当前安装的版本号是多少。

<img width="466" alt="image" src="https://github.com/aisuda/amis-widget/assets/85469054/396a28f6-341c-430f-a9c1-872029aa7a36">

**Comment by yyh1413** [comment]
起不来呀  报错信息同1楼一样

**Comment by wibetter** [comment]
线上的示例就是使用master分支构建的，本地也是可以正常运行的。
拉下master最新代码试下，确保删除node_modules和lock文件，重新执行下npm install。

**Comment by wibetter** [comment]
刚试下了下使用yarn安装依赖，确实有问题，先使用npm安装依赖吧。
