### ISSUE TITLE
自定义组件在编辑器中外观 配置控件尺寸后不生效

### ISSUE THREAD

**Issue by minzhenyu** [aisuda/amis-widget#32]
@wibetter 
https://github.com/aisuda/amis-widget/tree/master/src/frameworkFactory/vueFactory.tsx

这个文件中
```
render() {
      return <div ref={this.domRef}></div>;
   }
```
返回了div 样式没添上

**Comment by wibetter** [comment]
在自定义组件渲染时补上style，这个需要自定义组件开发者实现。
