### ISSUE TITLE
使用registerAmisEditorPlugin创建插件提示类型错误无法渲染

### ISSUE THREAD

**Issue by qyh613** [aisuda/amis-widget#33]
![20230831103120](https://github.com/aisuda/amis-widget/assets/67140048/e426a02f-3b6f-4228-98b7-1bdd46fbde5c)
![image](https://github.com/aisuda/amis-widget/assets/67140048/fd5e9069-d67d-44f2-b8e7-54c8c82244f9)

是不是需要 registerRendererByType 注册 amis 组件？
使用 registerRendererByType 创建的组件 怎么挂载到 amis-editor 组件上

**Comment by qyh613** [comment]
registerRendererByType 如何注册vue3组件，还是只能注册react组件

**Comment by wibetter** [comment]
@qyh613 还需要 registerRendererByType 注册 amis 组件，然后再通过registerAmisEditorPlugin挂载到amis-editor中。具体细节可以看下这个文档：https://aisuda.github.io/aisuda-docs/NPM%E7%BB%84%E4%BB%B6%E6%89%A9%E5%B1%95%E5%8C%85/%E5%8A%9F%E8%83%BD%E4%BB%8B%E7%BB%8D
