### ISSUE TITLE
form 开启debug，报错渲染不出，应该和json组件有关

### ISSUE THREAD

**Issue by nabaonan** [aisuda/amis-widget#34]
设置form为debug true报错,无法渲染，反正用到了json-view的应该都会报错，技术栈用的vite4+vue3
```json

{

  "type": "page",
  "body": [{
    "type": "input-rich-text",
    "label": "5555"

  },{
    "type": "form",
    "debug": true
  }]
}


```

<img width="1340" alt="image" src="https://github.com/aisuda/amis-widget/assets/17247526/07e07709-6b68-4383-b44a-2ab646518566">

**Comment by 2betop** [comment]
盲猜一下，`optimizeDeps.include` 添加 `react-json-view` 试试

如：

```js
optimizeDeps: {
  include: ['react-json-view'],
},
```

**Comment by nabaonan** [comment]
> ```js
> react-json-view
> ```

没有效果，还是报错,我看了amis源码里的fis-conf  中会对某些js做映射，比如
<img width="678" alt="image" src="https://github.com/aisuda/amis-widget/assets/17247526/b49bf254-b6d8-4c93-a6a6-9d7f40dd0a9e">，我启动amis源码倒是没有报错，不知道在哪里做了一些处理，和这个fis配置是否有关

**Comment by 2betop** [comment]
amis 源码是用的 vite 起的，不是 fis，fis 是用来编译 jssdk 用的

**Comment by nabaonan** [comment]
> jssdk

源码确实正常的，我新创建一个react版本的vite项目也是不正常的，源码对这块做了什么处理么，昨天看了有个amis-starter的项目，vite模式也不正常
