### ISSUE TITLE
拖动自定义组件，刷新页面后报错

### ISSUE THREAD

**Issue by 21sbaer** [aisuda/amis-widget#35]
![image](https://github.com/aisuda/amis-widget/assets/38722248/4fe36b8a-de23-446b-84df-dcf67bb825a9)

**Comment by wibetter** [comment]
出现这个问题的原因：自定义组件渲染器没有在编辑器渲染前加载。
解决方法：确保在编辑器渲染前，完成自定义组件的加载。
在线示例（https://aisuda.github.io/amis-widget/test/preview.html）因为没有控制自定义组件加载加载时机所以刷新后存在此类问题。
备注：爱速搭（amis商业化产品）不会存在此类问题。

**Comment by 21sbaer** [comment]
好的，多谢！
&nbsp;


小草
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月27日(星期五) 上午10:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aisuda/amis-widget] 拖动自定义组件，刷新页面后报错 (Issue #35)





 
出现这个问题的原因：自定义组件渲染器没有在编辑器渲染前加载。
 解决方法：确保在编辑器渲染前，完成自定义组件的加载。
 在线示例（https://aisuda.github.io/amis-widget/test/preview.html）因为没有控制自定义组件加载加载时机所以刷新后存在此类问题。
 备注：爱速搭（amis商业化产品）不会存在此类问题。
