### ISSUE TITLE
vue2 使用amis-widget，在amis-editor自定义组件时，无法正常展示

### ISSUE THREAD

**Issue by SunHengX** [aisuda/amis-widget#37]
大佬你好，我最近在研究这个低代码的平台，感觉amis非常适合我们，但是在使用过程中遇到了一些问题，因为我是一名后端的开发者，可能不太熟徐，请大佬帮我解决下困扰
![image](https://github.com/aisuda/amis-widget/assets/63703285/ef4f6bb2-8f00-4d50-9de9-b365e66b35bc)
![26a5c6bfd2a97091f7217959d8776bb](https://github.com/aisuda/amis-widget/assets/63703285/66953837-776f-4996-bc3e-15e4bd3c64dd)
![d4f89479307fb8a89bec09f8e971fac](https://github.com/aisuda/amis-widget/assets/63703285/49003ce2-31fc-4cb8-a074-c4a7e83e88bc)
![c7186770b8745141259b486c5e46d33](https://github.com/aisuda/amis-widget/assets/63703285/79c9c7f9-aefd-4871-a686-1481f52fc18e)

（备注：不知道有没有影响）我是用的是vue2和webpack4，在直接引用registerAmisEditorPlugin时我直接用的umd的，
在使用editor的时候，他说找不到对应的渲染器，内容区域显示类型错误，无法显示，
我就是按照上面截图的进行配置的
请大佬帮忙解答下

**Comment by wibetter** [comment]
@SunHengX  registerAmisEditorPlugin 只是用来注册一个editor插件，还需要使用registerRendererByType注册成一个ami渲染器才行（确保页面内容中能正常渲染自定义组件）。详细使用文档可以看这个：[NPM组件扩展包](https://aisuda.bce.baidu.com/aisuda-docs/NPM%E7%BB%84%E4%BB%B6%E6%89%A9%E5%B1%95%E5%8C%85/%E5%8A%9F%E8%83%BD%E4%BB%8B%E7%BB%8D)
