### ISSUE TITLE
demo中react自定义组件自己嵌套自己也存在问题, 会报''类型错误，无法渲染"

### ISSUE THREAD

**Issue by minzhenyu** [aisuda/amis-widget#4]
@demo中react自定义组件自己嵌套自己也存在问题, 会报''类型错误，无法渲染"

info-card.jsx 中添加了渲染子组件的代码
 <div className="body-container">
          {render('body', body) /*渲染孩子节点*/}
  </div>

scaffold = {
    type: 'react-info-card',
    label: 'react-info-card',
    name: 'react-info-card',
    body:[{
          type: 'wrapper',
          body:[
            {
              type: 'react-info-card',
            label: 'react-info-card',
            name: 'react-info-card',
            body:[]
          }
          ]
        }]
  };

**Comment by wibetter** [comment]
看一下这个react容器组件示例：https://github.com/aisuda/container-custom-widget-template，能正常实现多重嵌套。

**Comment by wibetter** [comment]
<img width="1414" alt="屏幕快照 2022-03-18 下午1 20 46" src="https://user-images.githubusercontent.com/11958920/158942299-3d400bcf-849e-4920-9529-71231460b9b6.png">

**Comment by minzhenyu** [comment]
我本地用demo是可以了,但是在自己的vue项目上升级amis,直接跑不起来, 
https://github.com/baidu/amis/issues/3974
monaco-editor 加载出现问题, 我看了下确实更新了版本并异步加载,是我webpack 配置的问题吗,实在找不到解决方案

**Comment by wibetter** [comment]
可能是monaco-editor 有版本冲突，建议直接使用amis中自带的monaco-editor版本，自己项目中不用单独再引入monaco-editor依赖，避免版本冲突。

**Comment by minzhenyu** [comment]
我本地项目npm list monaco-editor看了根本没依赖,本来项目能跑,一更新amis就跑不了了, 而且我是按照demo的版本写的

<img width="502" alt="image" src="https://user-images.githubusercontent.com/12856051/162165921-c2bd92be-ffc8-4f41-be5a-098a8be36472.png">

**Comment by minzhenyu** [comment]
最近amis 还更新过版本,之前monaco-editor@0.31.0报的另外的错https://github.com/babel/babel/discussions/14098,按照网上的降了版本可能是版本不一致还是报错,后来又node_module删掉,package.json重置,重新安装amis 还是报错,
基本就一直是下图报错了
<img width="669" alt="image" src="https://user-images.githubusercontent.com/12856051/162170088-21ba3ddd-34fb-44e3-b53f-d18e1e7a1723.png">

**Comment by minzhenyu** [comment]
我在demo项目里试着更新amis,报类型错误,无法渲染
`"amis": "1.8.0-beta.17",
    "amis-widget": "^1.3.5",`

**Comment by minzhenyu** [comment]
今天我重新更新了amis@beta版本报错减少了,这个是最初的问题,感觉有点方,是不是amis-editor也要最新的beta版本,等会试下,实在不行我只能去看更新是源码了
ps:下面是问题查资料说是可以降版本,其实之前试了项目依赖monaco-editor@0.30.1, 没生效,不知道是不是要全局安装
<img width="727" alt="image" src="https://user-images.githubusercontent.com/12856051/162351514-bfd9a4cc-764b-4b0c-963e-25cd638dd3a7.png">

**Comment by minzhenyu** [comment]
在之前更新的基础上,我本地项目重新装了 monaco-editor@0.30.1,然后把报错的amis 中的node_module里的monaco-editor包给删除了,现在能跑了,我分析是monaco-editor@0.31.1 里面webpack可能需要配置一些东西
amis@1.8.0-beta.17
│ └── monaco-editor@0.31.1
└── monaco-editor@0.30.1

**Comment by wibetter** [comment]
👍🏻

**Comment by VonnOoO** [comment]
我的monaco-editor也因为amis1.8.0种的0.33.0版本语法报错，试了网上的"@babel/plugin-proposal-class-properties"不起作用；
没办发，估计需要amis内部配置下，我只能暂时像上面一样降低monaco版本

**Comment by nwind** [comment]
试试 webpack 升级到 5

**Comment by minzhenyu** [comment]
@nwind 
<img width="383" alt="image" src="https://user-images.githubusercontent.com/12856051/163303855-b8275899-0632-4a0e-98f3-d9d093d98a8c.png">

**Comment by minzhenyu** [comment]
试过vue-cli 升级然后src 搬到新项目也没解决问题

**Comment by nwind** [comment]
monaco-editor-webpack-plugin 到 7.0.1 呢

**Comment by Lijie0981** [comment]
```
{
  "plugins": [
    "@babel/plugin-proposal-optional-chaining",
    "@babel/plugin-proposal-decorators",
    "@babel/plugin-proposal-class-properties"
  ]
}
```
试试这个呢？

**Comment by minzhenyu** [comment]
> monaco-editor-webpack-plugin 到 7.0.1 呢

monaco-editor-webpack-plugin 到 7.0.1也配置过,但是不起作用,按照npm配置过,vue.config.js下的configureWebpack
https://www.npmjs.com/package/monaco-editor-webpack-plugin,
我再试下

**Comment by nwind** [comment]
本质上是 0.31.0 版本开始加了 optional chaining，所以按说前面提到那个 @babel/plugin-proposal-optional-chaining 是关键

**Comment by minzhenyu** [comment]
> ```
> {
>   "plugins": [
>     "@babel/plugin-proposal-optional-chaining",
>     "@babel/plugin-proposal-decorators",
>     "@babel/plugin-proposal-class-properties"
>   ]
> }
> ```
> 
> 试试这个呢？



> monaco-editor-webpack-plugin 到 7.0.1 呢
vue.config.js 配置了,还是报错
    configureWebpack:{
        plugins: [new MonacoWebpackPlugin()],
        externals: {

        }
    },

**Comment by minzhenyu** [comment]
> ```
> {
>   "plugins": [
>     "@babel/plugin-proposal-optional-chaining",
>     "@babel/plugin-proposal-decorators",
>     "@babel/plugin-proposal-class-properties"
>   ]
> }
> ```
> 
> 试试这个呢？
plugins单独@babel/plugin-proposal-optional-chaining,全加都试了,都不行,下图框出来的参数不加会报其他错误https://babeljs.io/docs/en/babel-plugin-proposal-decorators,加上时候报错回到monaco-editor之前的报错
<img width="547" alt="image" src="https://user-images.githubusercontent.com/12856051/163309176-531338ba-811e-495c-9f20-660e3826f41a.png">

<img width="476" alt="image" src="https://user-images.githubusercontent.com/12856051/163309503-879ad42d-ce30-4ccc-86d6-a485b1f7f39e.png">

**Comment by Lijie0981** [comment]
> > ```
> > {
> >   "plugins": [
> >     "@babel/plugin-proposal-optional-chaining",
> >     "@babel/plugin-proposal-decorators",
> >     "@babel/plugin-proposal-class-properties"
> >   ]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 试试这个呢？
> > plugins单独@babel/plugin-proposal-optional-chaining,全加都试了,都不行,下图框出来的参数不加会报其他错误[https://babeljs.io/docs/en/babel-plugin-proposal-decorators,加上时候报错回到monaco-editor之前的报错](https://babeljs.io/docs/en/babel-plugin-proposal-decorators,%E5%8A%A0%E4%B8%8A%E6%97%B6%E5%80%99%E6%8A%A5%E9%94%99%E5%9B%9E%E5%88%B0monaco-editor%E4%B9%8B%E5%89%8D%E7%9A%84%E6%8A%A5%E9%94%99)
> 
> <img alt="image" width="547" src="https://user-images.githubusercontent.com/12856051/163309176-531338ba-811e-495c-9f20-660e3826f41a.png">
> 
> <img alt="image" width="476" src="https://user-images.githubusercontent.com/12856051/163309503-879ad42d-ce30-4ccc-86d6-a485b1f7f39e.png">

可能和你的webpack配置有关，我这配置了额外的plugins 就能编译过。

**Comment by minzhenyu** [comment]
> 

我这边是vue项目,用的vue-cli   webpack基本没做多余配置
`
module.exports = {
    publicPath: `/`,
    devServer: {
        proxy: {
            '/api/gf-admin': {
                target: 'http://172.18.22.35:9000/',
                ws: true,
                changeOrigin: true,
                pathRewrite: {
                    // '^/api/gf-admin/': '/'
                }
            }
        }
    },

    pages: {
        index: {
            // page 的入口
            entry: 'app/main.js'
        }
    },
    configureWebpack:{
        externals: {

        }
    },
    transpileDependencies:[
      
    ]
};
`
