### ISSUE TITLE
运行项目报错了

### ISSUE THREAD

**Issue by xmtkhlwk** [aisuda/amis-widget#7]
![image](https://user-images.githubusercontent.com/102603550/160630638-e8ffd351-b56d-4557-bb78-b73190203d0f.png)

**Comment by xmtkhlwk** [comment]
页面也出不来。

**Comment by wibetter** [comment]
请问你执行的是哪个命令，试一下：npm run dev

**Comment by xmtkhlwk** [comment]
我把流程写下：
1：执行npm install
2：执行npm  run  dev
自动打开了浏览器，然后就报这个错误，页面是空白的。浏览器的链接是：http://localhost/index.html。F12打开调试面板，就出现上述的错误了。如下是运行的日志：

D:\myworkspace\eclipse-new-framework\amis-widget>npm run dev

> amis-widget@1.3.3 dev
> amis dev

                                           
                             _/            
    _/_/_/  _/_/_/  _/_/          _/_/_/   
 _/    _/  _/    _/    _/  _/  _/_/        
_/    _/  _/    _/    _/  _/      _/_/     
 _/_/_/  _/    _/    _/  _/  _/_/_/        
                                           
                                           
当前版本：v1.5.0.

- [amis]开启调试模式...
> Starting dev server...
<i> [webpack-dev-middleware] wait until bundle finished
Build completed in 30.233s

assets by path *.js 44.4 MiB
  assets by chunk 22.1 MiB (id hint: vendors)
    asset vendors-include-loader_node_modules_monaco-editor_esm_vs_editor_editor_main_js.js 8.48 MiB [emitted] (id hint: vendors)
    asset vendors-node_modules_echarts_index_js.js 4.8 MiB [emitted] (id hint: vendors)
    + 42 assets
  + 63 assets
assets by info 2.87 MiB [immutable]
  assets by path fonts/ 1.13 MiB 13 assets
  assets by path img/ 1.74 MiB
    assets by path img/*.png 9.98 KiB 4 assets
    assets by path img/*.svg 1.73 MiB 3 assets
assets by path *.css 2.15 MiB
  asset index.css 1.95 MiB [emitted] (name: index)
  asset vendors-include-loader_node_modules_monaco-editor_esm_vs_editor_editor_main_js.css 196 KiB [emitted] (id hint: vendors)
asset index.html 761 bytes [emitted]
Entrypoint index 10.8 MiB (2.8 MiB) = index.css 1.95 MiB index.js 8.87 MiB 19 auxiliary assets
runtime modules 1.02 MiB 643 modules
orphan modules 2.27 MiB (javascript) 2.87 MiB (asset) [orphan] 122 modules
javascript modules 26.1 MiB
  modules by path ./node_modules/ 26.1 MiB
    cacheable modules 26 MiB 2974 modules
    + 4 modules
  modules by path ./demo2/ 18.9 KiB 17 modules
  modules by path ./src/ 19.9 KiB 6 modules
css modules 2.09 MiB
  modules by path ./node_modules/monaco-editor/esm/vs/ 145 KiB 70 modules
  modules by path ./node_modules/amis-widget-cli/src/editor/ 107 KiB 3 modules
  modules by path ./demo2/ 3.25 KiB 2 modules
  modules by path ./node_modules/amis/lib/ 1.74 MiB 2 modules
  + 1 module
./node_modules/markdown-it/node_modules/entities/lib/maps/entities.json 28.4 KiB [built] [code generated]
webpack 5.70.0 compiled successfully in 30019 ms
√ [amis]调试模式已开启！
> Listening at http://localhost:80

当前运行脚本:
 http://localhost:80/index.js
当前运行样式[可能不存在]:
http://localhost:80/index.css

**Comment by wibetter** [comment]
你改了什么内容吗？比如amis.config.js中的配置项，

**Comment by wibetter** [comment]
我这边刚重新安装后执行npm run dev是正常的，

**Comment by wibetter** [comment]
npm i 重新安装的时候删一下lock文件，

**Comment by xmtkhlwk** [comment]
可以啦，感谢刘总!

**Comment by xmtkhlwk** [comment]
项目运行起来了，但是组件旁边问号的组件说明都没有了呀，您会这样吗？ @wibetter 
![image](https://user-images.githubusercontent.com/102603550/161086034-a81cd4aa-18b0-42f0-9d84-d0d08d83e3e7.png)

**Comment by wibetter** [comment]
这个amis版本有问题，已经在amis中修复了，需要等外网发一版。
