### ISSUE TITLE
关于 vue3-amis-widget 

### ISSUE THREAD

**Issue by hyzx86** [aisuda/amis-widget#8]
文档中提到 有个 `vue3-amis-widget` 请问这个仓库开源了吗？
> 目前支持的技术栈：jQuery、vue2、react，vue3.0技术栈在**vue3-amis-widget**中支持

**Comment by wibetter** [comment]
还没有开始开发，预计6月份前会补上。

**Comment by hyzx86** [comment]
我看了 vue版本的factory ，原理跟vuera 差不多，
而且网上很多vue版本amis的集成都用的vuera，它支持 vue 和 react 组件的双向转换,但遗憾的是vuera 不支持vue3
是不是 可以考虑出个 支持vue3版本的 vuera 类似的组件，一劳永逸啊？

**Comment by wibetter** [comment]
好的，后面做的时候会参考您的建议，
