### ISSUE TITLE
通过renderAmis自定义一个容器组件  但是在编辑器里 容器组件里的内容编辑不了  是用法错了吗

### ISSUE THREAD

**Issue by Ding4514** [aisuda/amis-widget#9]
![image](https://user-images.githubusercontent.com/57136111/161372066-041195aa-7892-4081-a252-df13ba6a626d.png)
![image](https://user-images.githubusercontent.com/57136111/161372065-2f949aa1-c431-4fc8-9032-d837a052b17f.png)
![image](https://user-images.githubusercontent.com/57136111/161372138-c9ac0bdd-c665-430c-bfce-cb57eb5d64a4.png)

**Comment by wibetter** [comment]
请问你这个renderAmis是哪儿来的？

**Comment by Ding4514** [comment]
就是amis中的 
![image](https://user-images.githubusercontent.com/57136111/161373649-82249a99-9ed3-4104-aab5-13c53c03e6a1.png)

**Comment by wibetter** [comment]
你这样肯定会有问题，这个只是渲染内容，走个是独立的一套上下文，

**Comment by wibetter** [comment]
可以使用amis-widget实现容器类组件

**Comment by Ding4514** [comment]
好的  谢谢您
